=== zjdx1998/XML/XML_Group2_赶紧毕业_71117123张建东_71117124湛钊/1InformationModel/doubanSchema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- created by 赶紧毕业 Group2 71117123张建东 71117124湛钊 19/3/2020-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="MovieRank">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Retrieve"/>
				<xs:element ref="Movie" maxOccurs="250"/>
			</xs:sequence>
			<xs:attribute name="total" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="1"/>
						<xs:maxInclusive value="250"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Retrieve">
		<xs:complexType>
			<xs:attribute name="time" type="xs:date" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Movie">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Name"/>
				<xs:element ref="Rating"/>
				<xs:element ref="Category" maxOccurs="unbounded"/>
				<xs:element ref="Intro"/>
				<xs:element ref="Date"/>
				<xs:element ref="Length"/>
				<xs:element ref="Director"/>
				<xs:element ref="ScriptWriter" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="ActorList"/>
			</xs:sequence>
			<xs:attribute name="Rank" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="1"/>
						<xs:maxInclusive value="250"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Name">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="StandardName"/>
				<xs:element ref="OtherName" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="StandardName" type="xs:string"/>
	<xs:element name="OtherName" type="xs:string"/>
	<xs:element name="Rating" type="xs:decimal"/>
	<xs:element name="Category">
		<xs:complexType>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="剧情"/>
						<xs:enumeration value="喜剧"/>
						<xs:enumeration value="动作"/>
						<xs:enumeration value="爱情"/>
						<xs:enumeration value="科幻"/>
						<xs:enumeration value="动画"/>
						<xs:enumeration value="悬疑"/>
						<xs:enumeration value="惊悚"/>
						<xs:enumeration value="恐怖"/>
						<xs:enumeration value="犯罪"/>
						<xs:enumeration value="同性"/>
						<xs:enumeration value="音乐"/>
						<xs:enumeration value="歌舞"/>
						<xs:enumeration value="传记"/>
						<xs:enumeration value="历史"/>
						<xs:enumeration value="战争"/>
						<xs:enumeration value="西部"/>
						<xs:enumeration value="奇幻"/>
						<xs:enumeration value="冒险"/>
						<xs:enumeration value="灾难"/>
						<xs:enumeration value="武侠"/>
						<xs:enumeration value="情色"/>
						<xs:enumeration value="古装"/>
						<xs:enumeration value="家庭"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Intro">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="keyword"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="keyword" type="xs:string"/>
	<xs:element name="Date" type="xs:string"/>  
	<xs:element name="Length" type="xs:string"/>
	<xs:element name="Director" type="xs:string"/>
	<xs:element name="ScriptWriter" type="xs:string"/>
	<xs:element name="ActorList">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Actor" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Actor" type="xs:string"/>
</xs:schema>

=== zjdx1998/XML/EXP_Week4/DoubanMovie.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- created by 赶紧毕业 Group2 71117123张建东 71117124湛钊-->
<MovieRank total="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="doubanSchema.xsd">
	<Retrieve time="2020-03-02"/>
	<Movie Rank="1">
		<Name>
			<StandardName>肖申克的救赎</StandardName>
			<OtherName>月黑高飞(港)</OtherName>
			<OtherName>刺激1995(台)</OtherName>
			<OtherName>地狱诺言</OtherName>
			<OtherName>铁窗岁月</OtherName>
			<OtherName>消香克的救赎</OtherName>
		</Name>
		<Rating>9.7</Rating>
		<Category type="剧情"/>
		<Category type="犯罪"/>
		<Intro>20世纪40年代末，小有成就的青年银行家安迪（<keyword>蒂姆·罗宾斯 Tim Robbins
        </keyword> 饰）因涉嫌杀害妻子及她的情人而锒铛入狱。在这座名为肖申克的监狱内，
            希望似乎虚无缥缈，终身监禁的惩罚无疑注定了安迪接下来灰暗绝望的人生。未过多久，
            安迪尝试接近囚犯中颇有声望的瑞德（<keyword>摩根·弗里曼 Morgan Freeman</keyword>饰）
            ，请求对方帮自己搞来小锤子。以此为契机，二人逐渐熟稔，安迪也仿佛在鱼龙混杂、罪恶横生、
            黑白混淆的牢狱中找到属于自己的求生之道。他利用自身的专业知识，帮助监狱管理层逃税、洗黑钱，
            同时凭借与瑞德的交往在犯人中间也渐渐受到礼遇。表面看来，他已如瑞德那样对那堵高墙从憎恨转变
            为处之泰然，但是对自由的渴望仍促使他朝着心中的希望和目标前进。而关于其罪行的真相，似乎
            更使这一切朝前推进了一步……
        　　本片根据著名作家<keyword>斯蒂芬·金（Stephen Edwin King）</keyword>的原著改编。</Intro>
		<Date>1994-09-10</Date>
		<Length>142</Length>
		<Director>弗兰克·德拉邦特</Director>
		<ScriptWriter>弗兰克·德拉邦特</ScriptWriter>
		<ScriptWriter>斯蒂芬·金</ScriptWriter>
		<ActorList>
			<Actor>蒂姆·罗宾斯</Actor>
			<Actor>摩根·弗里曼</Actor>
			<Actor>鲍勃·冈顿</Actor>
			<Actor>威廉姆·赛德勒</Actor>
			<Actor>克兰西·布朗</Actor>
		</ActorList>
	</Movie>
</MovieRank>

=== zjdx1998/XML/XML_Group2_赶紧毕业_71117123张建东_71117124湛钊/2Transformation/movieDetail.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- created by 赶紧毕业 Group2 71117123张建东 71117124湛钊 19/3/2020 -->
<?xml-stylesheet type="text/xsl" href="movieDetail.xslt"?>
<MovieRank total="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="doubanSchema.xsd">
    <Retrieve time="2020-03-19" />
    <Movie Rank="2">
        <Name>
            <StandardName>霸王别姬</StandardName>
            <OtherName>再见，我的妾</OtherName>
            <OtherName>Farewell My Concubine</OtherName>
        </Name>
        <Rating>9.6</Rating>
        <Category type="剧情" />
        <Category type="爱情" />
        <Category type="同性" />
        <Intro>
            　　段小楼
            <keyword>（张丰毅）</keyword>
            与程蝶衣
            <keyword>（张国荣）</keyword>
            是一对打小一起长大的师兄弟，两人一个演生，一个饰旦，一向配合天衣无缝，尤其一出《霸王别姬》，更是誉满京城，为此，两人约定合演一辈子《霸王别姬》。但两人对戏剧与人生关系的理解有本质不同，段小楼深知戏非人生，程蝶衣则是人戏不分。　　段小楼在认为该成家立业之时迎娶了名妓菊仙
            <keyword>（巩俐）</keyword>
            ，致使程蝶衣认定菊仙是可耻的第三者，使段小楼做了叛徒，自此，三人围绕一出《霸王别姬》生出的爱恨情仇战开始随着时代风云的变迁不断升级，终酿成悲剧。
        </Intro>
        <Date>1993-01-01(中国香港)</Date>
        <Length>171</Length>
        <Director>陈凯歌</Director>
        <ScriptWriter>芦苇</ScriptWriter>
        <ScriptWriter>李碧华</ScriptWriter>
        <ActorList>
            <Actor>张国荣</Actor>
            <Actor>张丰毅</Actor>
            <Actor>巩俐</Actor>
            <Actor>葛优</Actor>
            <Actor>英达</Actor>
            <Actor>蒋雯丽</Actor>
            <Actor>吴大维</Actor>
            <Actor>吕齐</Actor>
            <Actor>雷汉</Actor>
            <Actor>尹治</Actor>
            <Actor>马明威</Actor>
            <Actor>费振翔</Actor>
            <Actor>智一桐</Actor>
            <Actor>李春</Actor>
            <Actor>赵海龙</Actor>
            <Actor>李丹</Actor>
            <Actor>童弟</Actor>
            <Actor>沈慧芬</Actor>
            <Actor>黄斐</Actor>
            <Actor>徐杰</Actor>
        </ActorList>
    </Movie>
</MovieRank>

=== zjdx1998/XML/EXP_Week5/detail1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- created by 赶紧毕业 Group2 71117123张建东 71117124湛钊 19/3/2020 -->
<?xml-stylesheet type="text/xsl" href="movieDetail.xslt"?>
<MovieRank total="100" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="doubanSchema.xsd">
    <Retrieve time="2020-03-19" />
    <Movie Rank="1">
        <Name>
            <StandardName>肖申克的救赎</StandardName>
            <OtherName>月黑高飞(港)</OtherName>
            <OtherName>刺激1995(台)</OtherName>
            <OtherName>地狱诺言</OtherName>
            <OtherName>铁窗岁月</OtherName>
            <OtherName>消香克的救赎</OtherName>
        </Name>
        <Rating>9.7</Rating>
        <Category type="剧情" />
        <Category type="犯罪" />
        <Intro>
            　　20世纪40年代末，小有成就的青年银行家安迪
            <keyword>（蒂姆·罗宾斯TimRobbins饰）</keyword>
            因涉嫌杀害妻子及她的情人而锒铛入狱。在这座名为肖申克的监狱内，希望似乎虚无缥缈，终身监禁的惩罚无疑注定了安迪接下来灰暗绝望的人生。未过多久，安迪尝试接近囚犯中颇有声望的瑞德
            <keyword>（摩根·弗里曼MorganFreeman饰）</keyword>
            ，请求对方帮自己搞来小锤子。以此为契机，二人逐渐熟稔，安迪也仿佛在鱼龙混杂、罪恶横生、黑白混淆的牢狱中找到属于自己的求生之道。他利用自身的专业知识，帮助监狱管理层逃税、洗黑钱，同时凭借与瑞德的交往在犯人中间也渐渐受到礼遇。表面看来，他已如瑞德那样对那堵高墙从憎恨转变为处之泰然，但是对自由的渴望仍促使他朝着心中的希望和目标前进。而关于其罪行的真相，似乎更使这一切朝前推进了一步……　　本片根据著名作家斯蒂芬·金
            <keyword>（StephenEdwinKing）</keyword>
            的原著改编。
        </Intro>
        <Date>1994-09-10(多伦多电影节)</Date>
        <Length>142</Length>
        <Director>弗兰克·德拉邦特</Director>
        <ScriptWriter>弗兰克·德拉邦特</ScriptWriter>
        <ScriptWriter>斯蒂芬·金</ScriptWriter>
        <ActorList>
            <Actor>蒂姆·罗宾斯</Actor>
            <Actor>摩根·弗里曼</Actor>
            <Actor>鲍勃·冈顿</Actor>
            <Actor>威廉姆·赛德勒</Actor>
            <Actor>克兰西·布朗</Actor>
            <Actor>吉尔·贝罗斯</Actor>
            <Actor>马克·罗斯顿</Actor>
            <Actor>詹姆斯·惠特摩</Actor>
            <Actor>杰弗里·德曼</Actor>
            <Actor>拉里·布兰登伯格</Actor>
            <Actor>尼尔·吉恩托利</Actor>
            <Actor>布赖恩·利比</Actor>
            <Actor>大卫·普罗瓦尔</Actor>
            <Actor>约瑟夫·劳格诺</Actor>
            <Actor>祖德·塞克利拉</Actor>
            <Actor>保罗·麦克兰尼</Actor>
            <Actor>芮妮·布莱恩</Actor>
            <Actor>阿方索·弗里曼</Actor>
            <Actor>V·J·福斯特</Actor>
            <Actor>弗兰克·梅德拉诺</Actor>
            <Actor>马克·迈尔斯</Actor>
            <Actor>尼尔·萨默斯</Actor>
            <Actor>耐德·巴拉米</Actor>
            <Actor>布赖恩·戴拉特</Actor>
            <Actor>唐·麦克马纳斯</Actor>
        </ActorList>
    </Movie>
    </MovieRank>
